#!/bin/bash

# このスクリプトをプロジェクトディレクトリのルートに配置して実行すると、RailsとDynamoDBの環境が立ち上がります

touch Gemfile

cat <<TEXT > Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gem "rails"
TEXT

touch Gemfile.lock

touch docker-compose.yml

cat <<TEXT > docker-compose.yml
services:
  dynamo-demo-db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local:latest
    container_name: dynamo-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 3000:3000
volumes:
  dynamodb-data:
networks:
  default:
    name: dynamo-demo-network

TEXT

touch Dockerfile

cat <<TEXT > Dockerfile
FROM ruby:3.4

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

CMD ["rails", "server", "-b", "0.0.0.0"]
TEXT

touch entrypoint.sh

cat <<TEXT > entrypoint.sh
#!/bin/bash
set -e

rm -f /app/tmp/pids/server.pid

bundle install

exec "\$@"
TEXT

docker-compose build

docker-compose run --rm app \
  bash -c "bundle install && bundle exec rails new . --force --skip-docker --skip-keeps --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-action-view --skip-active-job --skip-active-storage --skip-action-cable --skip-test --skip-ci"

docker-compose up -d